### PR TITLE
Draggable addition

### PR DESCRIPTION
**Pull request by adamclark64**
I had an issue with a text box at the bottom of the slack web app and the 'command box' appending below so I couldn't use it.  Because there was already an issue open requesting the 'command box' to appear above the text box I felt like giving the user the ability drag the 'command box'  to the most convenient sport on the page seems like the best solution.  
I am not sure if there should be some indicator to the user that the box is draggable or if it should be implied. I think can be discussed but the functionality is a big overall enhancement.
I also wonder if this version of 'react-draggable' is the most stable for prod.. very new to contributing. I appreciate any feedback!

### CODE REVIEW

**Comment by adamclark64** [comment]
[https://github.com/jessepollak/command/issues/14](this issue) along with my own slack text box issue made me feel this was a good addition

**Comment by jessepollak** [comment]
Oh my — this is so wonderful! What an elegant solution.

dancing-happy-cartoons-10UeedrT5MIfPG

**Comment by jessepollak** [comment]
p.s. @adamclark64 — I've added you as a collaborator on the repository, so you now have the ability to merge PRs and branch on the repo. This is my general policy for all open source work I do: when I accept a PR from someone else, I give them commit access. I think it encourages collaboration and divests power from me.

Would love to have more contributions, if you're interested!

**Comment by adamclark64** [comment]
Thanks for the kind words and addition! Very happy to keep contributing!
axu6dFuca4HKM

**Pull request merged**
